docs: Added comment for handling equal numbers in if/if1.rs `bigger` function
rust-lang/rustlings pull request #1866
Opened 2024-02-28 13:22 UTC by guizo792

Added a clarifying comment in the `if/if1.rs bigger` function to explicitly mention the behavior when both input numbers are equal.

2024-03-12 21:37 UTC, mo8it approved these changes

2024-03-15 13:33 UTC, shadows-withal requested changes

2024-03-15 13:33 UTC, shadows-withal commented on exercises/03_if/if1.rs
> +    // If both numbers are equal, any of them is returned.
```suggestion
    // If both numbers are equal, any of them can be returned.
```

2024-03-15 19:56 UTC, shadows-withal approved these changes

2024-03-15 19:56 UTC, merged

2024-03-15 19:56 UTC, shadows-withal commented
@all-contributors please add @guizo792 for content