fix: use trait objects for try_from_into
rust-lang/rustlings pull request #693
Opened 2021-04-04 17:45 UTC by tlyu

Use `Box<dyn error::Error>` to allow solutions to use `?` to propagate
errors.  In the tests, explicitly check `is_ok()` instead of trying to
force the error type to `String` (or other `PartialEq` type) using
`assert_eq!()`.

2021-04-04 17:45 UTC, tlyu commented
This should fix #691.

2021-04-04 20:20 UTC, AbdouSeck requested changes
Hi @tlyu, this is a great idea. Thanks for both the issue and the PR. While you're already in the `conversions` exercises, would you mind updating the [`from_str.rs`](https://github.com/rust-lang/rustlings/blob/main/exercises/conversions/from_str.rs) exercise as well? The signature implementation of the `std::str::FromStr` trait could use an update similar to the one done here.

Thank you!
Abdou

2021-04-05 00:03 UTC, tlyu commented
Thanks for the review! I added a change for `from_str.rs` as well. I didn't try to propagate the error from `parse::<usize>()` in that exercise, so I didn't run into that problem. The difference is that with `try_from_into.rs`, there might be a lot of code repetition if the `?` operator isn't usable for error propagation. (This is especially true with the tuple implementation, because as far as I can tell, it's not possible to directly iterate over tuples.)

2021-04-05 11:24 UTC, AbdouSeck approved these changes
Looks great. Thank you!

2021-04-05 11:26 UTC, merged

2021-04-05 11:27 UTC, AbdouSeck commented
@all-contributors add @tlyu for code and content

2021-05-13 00:10 UTC, PhilMiller commented
(newcomer to Rust here; I'm encountering this as I work through the exercises)

Being able to use `?` to propagate errors is a definite improvement in the solution to `try_from_into`, and in parsing failures in `from_str`.

However, for bad value cases in `from_str` (e.g. wrong array length, or empty name string), it becomes very obscure how one should write the `Err(...)` to be returned. Am I supposed to implement and return a concrete type? Someone on Discord (`cysant`) suggested `Err("error".into())`, which works, but I have no idea what actual type it's constructing/converting.

2021-05-16 16:42 UTC, tlyu commented
> (newcomer to Rust here; I'm encountering this as I work through the exercises)
> 
> Being able to use `?` to propagate errors is a definite improvement in the solution to `try_from_into`, and in parsing failures in `from_str`.
> 
> However, for bad value cases in `from_str` (e.g. wrong array length, or empty name string), it becomes very obscure how one should write the `Err(...)` to be returned. Am I supposed to implement and return a concrete type? Someone on Discord (`cysant`) suggested `Err("error".into())`, which works, but I have no idea what actual type it's constructing/converting.

I opened #755 to add hints that should help with this. Please give feedback there if you like. Thanks!

2021-05-17 15:36 UTC, dahifi commented
What's the idiomatic version of this look like now? 

Specifically looking at this one, it seems a bit hairy. https://github.com/alexxroche/rustlings-idiomatic-solutions/blob/master/exercises/conversions/try_from_into.rs_/try_from_into_match.rs