feature: improve error_handling exercises
rust-lang/rustlings pull request #772
Opened 2021-06-07 04:12 UTC by tlyu

Move result1 to errors4 and put it in the error handling section. Fixes #719.

Add new exercises errors5 and errors6, to introduce boxed errors and
custom error enums more gently. Delete errorsn, because it tried to do
too much too soon. Fixes #756.

2021-06-09 15:57 UTC, yaahc requested changes

2021-06-09 15:57 UTC, yaahc commented on exercises/error_handling/errors5.rs
> +            CreationError::Zero => "Number is zero",
```suggestion
            CreationError::Negative => "number is negative",
            CreationError::Zero => "number is zero",
```

Error messages should be lower case so they concatenate with other error messages nicely

2021-06-09 15:57 UTC, yaahc commented on exercises/error_handling/errors6.rs
> +        .or(Err(ParsePosNonzeroError::CreationError))
This should use `map_err` and wrap the original error

That plus the above makes me think this belongs in that advanced error section you suggested

2021-06-09 15:57 UTC, yaahc commented on exercises/error_handling/errors6.rs
> +    CreationError,
this should wrap the source error, also, the Error variant's shouldn't include `Error` in their identifier.

```suggestion
    Creation {
        source: CreationError,
    }
```

2021-06-09 18:41 UTC, tlyu commented
Thanks for the review! I agree with most of your changes.

I was planning to have `map_err` in one of the advanced exercises, but now that we've talked about passing functions instead of closures to `map_err` (because closures aren't used yet at this point in the exercise sequence), I guess it could go in this exercise.

Is there a consensus for error enum variants with payloads? I think I've seen both 1-tuple structs and structs with named fields. Are there tradeoffs involved? (I suspect there are, involving public vs private visibility of fields, but I'm not sure.)

`std::num::ParseIntError` does have a payload, though it's a private one at the moment, so I guess we shouldn't wrap that?

2021-06-09 18:47 UTC, yaahc commented
> Is there a consensus for error enum variants with payloads? I think I've seen both 1-tuple structs and structs with named fields. Are there tradeoffs involved? (I suspect there are, involving public vs private visibility of fields, but I'm not sure.)

I don't think there is a clear consensus. There should be no difference in field visibility since all fields in enums are pub. The main difference is how the constructor is exposed. For a struct variant it uses the constructor syntax, but for unit variants the compiler essentially adds a function with the same name for the constructor. And I think I can see where you're going with this question. 

```rust
enum WrappingError {
    Inner(InnerError),
}

struct InnerError;

fn main() {
    Err::<(), _>(InnerError).map_err(WrappingError::Inner);
}
```

This is possible with tuple variants but not with struct variants, so it will probably be easiest to teach the tuple version since it provides the needed conversion function out of the box.

2021-06-09 18:51 UTC, yaahc commented
> `std::num::ParseIntError` does have a payload, though it's a private one at the moment, so I guess we shouldn't wrap that?

I don't understand what you mean. The ParseIntPayload is internal so we don't have to worry about it, but if anything the fact that they're not all identical and they have different runtime instantiations of that type means that we really need to wrap it, if we try to replace it with our own equivalent error type we will probably provide less information than the original error did.

2021-06-09 19:56 UTC, tlyu commented
> I don't understand what you mean. The ParseInt payload is internal so we don't have to worry about it, but if anything the fact that they're not all identical and they have different runtime instantiations of that type means that we really need to wrap it, if we try to replace it with our own equivalent error type we will probably provide less information than the original error did.

Yeah, I guess you're right. Even if we can't make decisions based on those private variants, they're still relevant for display purposes.

2021-06-09 20:32 UTC, tlyu commented
> This is possible with tuple variants but not with struct variants, so it will probably be easiest to teach the tuple version since it provides the needed conversion function out of the box.

I hadn't realized that tuple struct constructors actually were proper functions! I thought they were special struct expression syntax that happened to look like function calls. I'm not sure this exercise is the right place to introduce that concept. Or maybe it is? It seems likely to cause confusion if it hasn't been mentioned before.

2021-06-09 20:35 UTC, yaahc commented
> I hadn't realized that tuple struct constructors actually were proper functions! I thought they were special struct expression syntax that happened to look like function calls. I'm not sure this exercise is the right place to introduce that concept. Or maybe it is? It seems likely to cause confusion if it hasn't been mentioned before.

hehe, yea. This comes up when you're re-exporting items in a library. If you a type alias to bring it in it will only import the type, but not the function, where as if you export it with a `pub use` it will bring in all items with the same name from all 3 namespaces.

2021-06-10 18:25 UTC, yaahc reviewed
lgtm

2021-06-24 12:12 UTC, fmoko approved these changes
i trust your judgement @yaahc

2021-06-24 12:12 UTC, merged